### ISSUE TITLE
Prepare to change summation of urgency

### ISSUE THREAD

**Issue by lekroll** [zidatalab/ets-dashboard#1]
With the next data revision, urgency will have a "Gesamt" category, so current behaviour has to change to filter for "Gesamt" if this happens. New behaviour has to be synchronized with backend team @edg-stg

**Comment by lekroll** [comment]
Do you close your Issues @Inoakabu ? Asking for a friend 😉

**Comment by Inoakabu** [comment]
Sometime - but sometimes I just wanna see the world burn.

Glaube manchmal ist eher das Problem, dass es mehrere Issues gibt :D Versuche ab und an aufzuräumen, wird ja sonst auch natürlich verwirrend
