### ISSUE TITLE
Bundesländer ohne Daten ausblenden

### ISSUE THREAD

**Issue by edg-stg** [zidatalab/ets-dashboard#15]
insbesondere MV und SH

**Comment by Inoakabu** [comment]
Also statt dass "Es sind keine Daten vorhanden" gezeigt wird, sollen die Auswahlbundesländer ausgeblendet werden?

Hmmmm muss ich mal sehen wie ich das abgreife

**Comment by edg-stg** [comment]
ein hinweis wäre ok, aber wenn ich zB MV anklicke, blinken die grauen Kästen und sonst passiert nichts.

**Comment by Inoakabu** [comment]
Ich frag nur, weil wir haben ja den Hinweis, dass keine Daten dazu verfügbar sind

**Comment by edg-stg** [comment]
ich sehe keinen hinweis.
