### ISSUE TITLE
Hinweis einfügen: Beta-Version

### ISSUE THREAD

**Issue by edg-stg** [zidatalab/ets-dashboard#16]
Titel des DB bitte ändern in "Zahlen und Fakten zum 116117 Terminservice - Beta-Version"
und darunter Hinweis:
"Dieses Dashboard befindet sich noch in der Entwicklung. Aufbau und Darstellung sowie Kennzahlen und deren Operationalisierung können sich noch ändern. Bei Fragen wenden Sie sich bitte an das Zi."

**Comment by Inoakabu** [comment]
Wo hättest du diese Infos gern? Sehr prominent oder eher als hinweiß box etwas weniger aufdringlich?

**Comment by edg-stg** [comment]
Direkt oben, also direkt unter dem Titel (als Paragraph in normaler Schrift). Nicht aufdringlich, aber immer da.
