### ISSUE TITLE
Übersichtsseite: 2 Anteile (%) statt 3 Zahlen

### ISSUE THREAD

**Issue by edg-stg** [zidatalab/ets-dashboard#24]
mit @lekroll abgesprochen:
Auf der Übersichtsseite bitte die drei Plots entfernen, außerdem statt der 3 Kacheln mit Zahlen nur noch zwei Kacheln, nämlich:
- Terminangebot: "XX % des Terminangebots wurden gebucht" (= gebuchteTermine/TermineImAngebot)
- Vermittlungswünsche/Nachfrage: "YY % der Vermittlungswünsche waren erfolgreich" (= erfolgreicheVermittlungswünsche/Vermittlungswünsche)

Weitere Anpassungen der Übersichtsseite/des Dashboards besprechen wir demnächst gemeinsam.

**Comment by Inoakabu** [comment]
Erledigt - daten mit Edgar gegen gecheckt
