### ISSUE TITLE
status "gebucht_pat_noshow" mitberücksichtigen

### ISSUE THREAD

**Issue by edg-stg** [zidatalab/ets-dashboard#27]
https://github.com/zidatalab/ets-dashboard/blob/338c95015b6d6280a5b205ff564b334ff656580f/src/app/components/dashboard/dataQueries/eTerminService/makeETerminServiceData.ts#L126

dort bitte bei der gesamtzahl dataAppointmentDemand auch den Status gebucht_pat_noshow mitberücksichtigen, ebenso bei dataAppointmentDemandArranged

**Comment by Inoakabu** [comment]
`if (
            (item.nachfrage_group_status === "keine_buchung")
            || (item.nachfrage_group_status === "gebucht_arzt_abgesagt")
            || (item.nachfrage_group_status === "erfolgreich_gebucht")
            || (item.nachfrage_group_status === "gebucht_pat_abgesagt")
            || (item.nachfrage_group_status === "gebucht_pat_noshow")

          ) {
            resAppointmentDemand.push({ total: item['nachfrage_Anzahl'], date: this.localDateParser(item['nachfrage_reference_date']) })
            dataAppointmentDemand += item.nachfrage_Anzahl
          }`
          
`if ((item.nachfrage_group_status === "erfolgreich_gebucht")
            || (item.nachfrage_group_status === "gebucht_pat_abgesagt")
            || (item.nachfrage_group_status === "gebucht_pat_noshow")
          ) {
            resAppointmentDemandArranged.push({ total: item['nachfrage_Anzahl'], date: this.localDateParser(item['nachfrage_reference_date']) })
            dataAppointmentDemandArranged += item.nachfrage_Anzahl
          }`
          
          Das wäre was du wolltest?

**Comment by edg-stg** [comment]
ja, genau

**Comment by Inoakabu** [comment]
Ist live
