### ISSUE TITLE
Add Badge to Planungsansicht for Sum of all Slots displayed

### ISSUE THREAD

**Issue by lekroll** [zidatalab/ets-dashboard#37]
With "Planungsansicht" currently users see a map of slots by filters. But they do not know the totals for the slots displayed. So i think we need a badge to display the totals as in "Zeitreihen" view.

**Comment by lekroll** [comment]
And Stand is missing on planungsansicht, too.

So 2 tasks:

- [ ] Add Totals
- [ ] Add time of data aggregation "Stand"

**Comment by Inoakabu** [comment]
I do not really get it. 

What's the total of something based off of filtered values by Postal Codes?
