### ISSUE TITLE
Mecklenburg-Vorpommern und Schleswig-Holstein "keine Daten" anzeigen

### ISSUE THREAD

**Issue by edg-stg** [zidatalab/ets-dashboard#5]
nicht hart kodieren für diese beiden BL, sondern dynamisch

**Comment by Inoakabu** [comment]
Das hab ich quasi schon mal eigenständig entschieden, weil es mehr Sinn ergibt. :)
Du hättest aber keine neue Issue dazu erstellen brauchen haha

**Comment by edg-stg** [comment]
achso. duplikat von #4
